---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false


# Install ansible
addons:
  apt:
    packages:
    - python-pip

services:
  - docker

env:
  global:
    - ANSIBLE_CONFIG=tests/test.cfg
  matrix:
    - TEST=default
    - TEST=opt

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # syntax check
  - "ansible-playbook -i tests/$TEST/inventory tests/$TEST/test.yml --syntax-check"
  # run playbook
  - "ansible-playbook -i tests/$TEST/inventory tests/$TEST/test.yml --connection=local --sudo"
  # Run the playbook again, checking idempotence.
  - >
    ansible-playbook -i tests/$TEST/inventory tests/$TEST/test.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  # pinging host, using bootstrapped python
  - "ansible -i tests/$TEST/inventory all -m ping"
