---
# tasks file for sigma.coreos-bootstrap

- name: Run bootstrap.sh
  script: bootstrap.sh creates={{coreos_pkg_home}}/.bootstrapped
  environment:
    PKG_HOME: "{{coreos_pkg_home}}"
    PYPY_VERSION: "{{coreos_pypy_version}}"
    PYPY_FLAVOR: "{{coreos_pypy_flavor}}"
    PYPY_HOME: "{{coreos_pypy_home}}"
    PYPY_DOWNLOAD_URL: "{{coreos_pypy_url}}"

- name: Get ssl certs path
  shell: >-
    {{coreos_python_interpreter}} -c
    'from __future__ import print_function; import ssl; print(ssl.get_default_verify_paths().openssl_capath)'
  register: ssl_path

- name: create ssl certs dir
  sudo: true
  file: dest={{ssl_path.stdout | dirname}} state=directory

- name: Make sure ssl certs are found
  sudo: true
  file: src={{coreos_ssl_certs}} dest={{ssl_path.stdout}} state=link

- name: Get get-pip.py
  get_url: url={{coreos_pip_script}} dest={{coreos_pkg_home_bin}}/get-pip.py mode=0755

- name: Install pip
  shell: "{{coreos_python_interpreter}} {{coreos_pkg_home_bin}}/get-pip.py creates={{coreos_pypy_home}}/bin/pip"
