---
# tasks file for sigma.coreos-bootstrap

- name: Make sure a version of python exists
  script: bootstrap.sh creates=/etc/ansible/facts.d/bootstrap.fact
  environment: "{{bootstrap_environment}}"

- name: Load bootstrap facts
  setup: filter=ansible_local

- name: Re-run bootstrap if python upgrade needed
  script: bootstrap.sh
  environment: "{{bootstrap_environment}}"
  when: coreos_pypy_version != ansible_local.bootstrap.pypy.version
  register: rebootstrap

- name: Reload bootstrap facts
  setup: filter=ansible_local
  when: rebootstrap.changed

- name: Get ssl certs path
  shell: "{{bootstrap_ssl_path}}"
  register: ssl_path
  changed_when: False

- name: create ssl certs dir
  sudo: true
  file: dest={{ssl_path.stdout | dirname}} state=directory

- name: Make sure ssl certs are found
  sudo: true
  file: src={{coreos_ssl_certs}} dest={{ssl_path.stdout}} state=link
