---
# tasks file for sigma.coreos-bootstrap

- name: Run bootstrap.sh
  script: bootstrap.sh creates={{coreos_pkg_home}}/.bootstrapped
  environment:
    PKG_HOME: "{{coreos_pkg_home}}"
    PYPY_VERSION: "{{coreos_pypy_version}}"
    PYPY_HOME: "{{coreos_pypy_home}}"

- name: Get get-pip.py
  shell: curl -Lo {{coreos_pkg_home_bin}}/get-pip.py {{coreos_pip_script}} creates={{coreos_pkg_home_bin}}/get-pip.py

- name: Install pip
  shell: "{{ansible_python_interpreter}} {{coreos_pkg_home_bin}}/get-pip.py creates={{coreos_pypy_home}}/bin/pip"
